default: &default
  adapter:  <%= ENV.fetch('DB_ADAPTER')        { 'mysql2' } %>
  host:     <%= ENV.fetch('DB_HOST')           { '127.0.0.1' } %>
  port:     <%= ENV.fetch('DB_PORT')           { '3306' } %>
  pool:     <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  username: <%= ENV.fetch('DB_USERNAME')       { 'root' } %>
  password: <%= ENV.fetch('DB_PASSWORD')       { 'secret' } %>

development:
  <<: *default
  database: <%= ENV['DB_DATABASE'] %>_development
test:
  <<: *default
  database: <%= ENV['DB_DATABASE'] %>_test

production:
  <<: *default
  database: <%= ENV['DB_DATABASE'] %>_production
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
